// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dictionary} from '../models';

export function Greet(arg1:string):Promise<string>;

export function Lookup(arg1:string):Promise<dictionary.LookupResultWithSuggestion>;
